# Site settings
title: Learn More about Davis Tui
email: davis.tui@gmail.com
description: Welcome to Davis Tui's personal blog, where you'll find helpful tips and insights on technology, low-code, sales, and productivity
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davistui.com" # the base hostname & protocol for your site
twitter_username: honest2davis
github_username:  davistui
permalink: /blog/:title
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-figure

# Build settings
markdown: kramdown
